version: "3.8"

services:
  bot:
    build: .
    container_name: andromeda_bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .wwebjs_auth:/usr/src/app/.wwebjs_auth
      - .wwebjs_cache:/usr/src/app/.wwebjs_cache
